#pmake: serv remote os_nt cpu_axp nov axp

host_cpu = axp
host_os  = nt

gui   = 1
os    = nt
srv   = nov
cpu   = axp
which = SERVER
type  = remote_link

extra_objs = novnt.obj

!include $(trap_dir)/master.mif
